[package]
name = "rl"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = "2.0.1"
burn = { version = "0.20.0", features = ["autodiff", "cuda", "ndarray"] }   
burn-cubecl = "0.20.0"
macroquad = "0.4.14"
num = "0.4.3"
parry2d = "0.25.3"
rand = "0.9.2"
