[package]
name = "rl"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = "2.0.1"
burn = { version = "0.20.0-pre.4", features = ["autodiff", "cuda", "ndarray"] }   
macroquad = "0.4.14"
num-complex = "0.4.6"
parry2d = "0.25.3"
rand = "0.9.2"
